### ISSUE TITLE
How to use docker-compose.yml ?

### ISSUE THREAD

**Issue by sebastienhouzet** [delfer/docker-alpine-ftp-server#14]
Hello,

I have tried to use your image with docker-compose

````
version: '3'
services:
  sftp:
    image: delfer/alpine-ftp-server
    environment:
      - USERS="usertest|password0123456789"
    volumes:
      - ./www:/var/www:delegated
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
````

But i have this error during up, Get env USERS not working "illegal character with code 34 at position 0"

````
$ docker-compose up
Recreating sftp_sftp_1 ... done
Attaching to sftp_sftp_1
sftp_1  | BusyBox v1.30.1 (2019-10-26 11:23:07 UTC) multi-call binary.
sftp_1  |
sftp_1  | Usage: deluser [--remove-home] USER
sftp_1  |
sftp_1  | Delete USER from the system
sftp_1  | adduser: illegal character with code 34 at position 0
sftp_1  | chown: unknown user/group "usertest:"usertest
`````
I have tried without environment: - USERS="usertest|password0123456789"
But the defaut user ftp, not working alose.

I dont know with user are not created with docker-compose.
