### ISSUE TITLE
how to prevent ftp user to go to parent directory?

### ISSUE THREAD

**Issue by mdallau** [delfer/docker-alpine-ftp-server#19]
I noticed that when I connect to the ftp-server I am able to go to the parent directory and even to other directories in the root.
How can I prevent the ftp user to go other directories?

**Comment by gadget1999** [comment]
add the following lines to vsftpd.conf:

chroot_local_user=YES
allow_writeable_chroot=YES

**Comment by TrueOsiris** [comment]
This is now in the default file.

**Comment by delfer** [comment]
Reverted https://github.com/delfer/docker-alpine-ftp-server/pull/22

**Comment by albanm** [comment]
How is it possible to get this functionality since the commit was reverted ?

**Comment by Jormodn** [comment]
Any feature plans to get that feature after that revert?

**Comment by G3z** [comment]
to use this options:
- I created a `vsftpd.conf` file with the content taken from the [repo](https://github.com/delfer/docker-alpine-ftp-server/blob/master/vsftpd.conf) 
- uncommented `chroot_local_user=YES` and added `allow_writeable_chroot=YES` just below it
- set `root:root` as owner and group of the file (otherwise ftp server did not respond)
- mounted the file inside the container `- "./vsftpd/vsftpd.conf:/etc/vsftpd/vsftpd.conf"`

**Comment by ShubhTakale** [comment]
> I noticed that when I connect to the ftp-server I am able to go to the parent directory and even to other directories in the root. How can I prevent the ftp user to go other directories?

How are you connecting, I am not able to connect?

**Comment by alexleach** [comment]
Personally I changed the folder permissions:

In `docker-compose.yaml`:

```yaml
version: "3.0"

services:
  ftp:
    image: delfer/alpine-ftp-server
    environment:
      - USERS=user1|password1|/srv/ftp/user1 user2|password2|/srv/ftp/user2
    volumes:
      - /srv/ftp:/srv/ftp
[...]
```

Bring the container up, and let the container make the user folders.

Then in the host, remove global read permissions from `/srv/ftp`, and read and execute permissions from `/srv/ftp/*`:

```sh
$ sudo chmod o-r /srv/ftp
$ sudo chmod o-rx /srv/ftp/*
```

I think this could quite easily be put into the startup script, I'll see about creating a pull request...

**Comment by Bumpay** [comment]
> to use this options:
> 
> * I created a `vsftpd.conf` file with the content taken from the [repo](https://github.com/delfer/docker-alpine-ftp-server/blob/master/vsftpd.conf)
> * uncommented `chroot_local_user=YES` and added `allow_writeable_chroot=YES` just below it
> * set `root:root` as owner and group of the file (otherwise ftp server did not respond)
> * mounted the file inside the container `- "./vsftpd/vsftpd.conf:/etc/vsftpd/vsftpd.conf"`

As soon as I add your changes I am not able to connect anymore:

`Connection attempt failed with "ECONNREFUSED - Connection refused by server".`

Any ideas why?

compose.yml:
```yaml
ftp:
  container_name: ftp
  image: delfer/alpine-ftp-server
  ports:
    - "21000:21"
    - "21001-21009:21001-21009"
  environment:
    USERS: ftp-admin|password|/server/server-data
  volumes:
    - ./:/server
    - ./vsftpd.conf:/etc/vsftpd/vsftpd.conf
  restart: unless-stopped
```
