### ISSUE TITLE
Container dies after: "adduser: user 'ftp_user' in use"

### ISSUE THREAD

**Issue by dominik-stypula-polcode** [delfer/docker-alpine-ftp-server#38]
I'm using it in `docker-compose.yml` as follows:
```
    ftp:
        image: 'delfer/alpine-ftp-server'
        volumes:
            - ./ftp_dir:/home/ftp_user/dir
        ports:
            - '21:21'
            - '21000-21010:21000-21010'
        environment:
            - USERS=ftp_user|ftp_user|/home/ftp_user/dir
            - ADDRESS=localhost
```
After first run `docker-compose up` it's OK, but the second run always complains about user already existing, and container dies.
This should check if the user `ftp_user` already exists if container is not destroyed.
```
ftp_1: adduser: user 'ftp_user' in use
.....
project_ftp_1 exited with code 0
```
