### ISSUE TITLE
container undeterministically dies directly after startup

### ISSUE THREAD

**Issue by derMart** [delfer/docker-alpine-ftp-server#48]
I have the problem, that the docker container sometimes! exits right after startup with exit code 0 showing only `ftp-server_1      | process has died, quitting` in the output but nothing else, no error message or anything. Restarting the container sometimes fixes the problem, very weird. Here is the configuration using docker-compose
```
ftp-server:
  environment:
    - USERS=user|pass|/home/user|${uid}
    - ADDRESS=localhost
  image: delfer/alpine-ftp-server
  ports:
    - '21:21/tcp'
    - '21000-21010:21000-21010/tcp'
  volumes:
    - './static_server/data:/home/user'
```
where ${uid} is an environment variable.

**Comment by BenasB** [comment]
Seems like I'm experiencing something similar in #49 After more testing, it sometimes starts correctly, did not face any issues with Windows though

**Comment by BenasB** [comment]
I can see there's a [revert-22-master](https://hub.docker.com/layers/delfer/alpine-ftp-server/revert-22-master/images/sha256-1c97abac2c6314c2313e2d2cf1069284a1bc7c596dd2463e4c81a80da155f1e3?context=explore) tag in docker hub, I tried it out and it seems like I don't get this error (at least after ~5 times). Although stopping the container is for some reason taking longer. Would you mind trying that tag @derMart ?

**Comment by derMart** [comment]
I tried the `revert-22-master` tag. As this is undeterministic it is hard to tell, but from now only 2 startups problem does not appear (EDIT: will report back when I got some more experience). But I also experience that the container is taking much longer to shutdown. Tbh, that is pretty annoying ...

@delfer But this might be a hint that there is a regression going on between `revert-22-master` and current release

**Comment by delfer** [comment]
@derMart @BenasB is this problem occurs with the latest image version? Whit Docker version do you use? Can you provide container output?

**Comment by 9en9i** [comment]
@delfer. I have the same problem. I'm using Docker Desktop 4.25.1 on a Mac with M1 chip. The latest version of the image. MacOS version is 14.1.1. Container output:
```
adduser: user 'user' in use
process has died, quitting
```
My docker compose file looks like this:
```
x-ftp-connection: &ftp-connection
  USERS: $CORE__CDN_FTP_USER|$CORE__CDN_FTP_PASSWORD|/home/local

services:
  storage:
    image: delfer/alpine-ftp-server
    environment: *ftp-connection
    volumes:
      - ./ftp_data:/home/local
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
```

**Comment by johanan1** [comment]
Same here. Container dies randomly during startup. Running Macbook Pro M3 and Docker Desktop 4.27.0.

**Comment by Dishank-Kheni** [comment]
same here. container dies randomly. sometime wok sometimes doesn't.

**Comment by JonathanFinch-awin** [comment]
Same here, happening non-deterministically when running on GitHub Actions.

```
  /usr/bin/docker version --format '{{.Server.APIVersion}}'
  '1.48'
  Docker daemon API version: '1.48'
  /usr/bin/docker version --format '{{.Client.APIVersion}}'
  '1.48'
  Docker client API version: '1.48'
```

```
Print service container logs: 7d0def90b4a540378f40f2fa04dc39f4_delferalpineftpserver_15622f
/usr/bin/docker logs --details 403c487f1264cbdb6a830f19555abbcefcfa0a2a0f6f871c38af6a1d1849ac2e
 adduser: /ftp/ftpuserone: No such file or directory
 Changing password for ftpuserone
 passwd: password for ftpuserone changed by root
 process has died, quitting
 New password: 
 Retype password: 
Stop and remove container: 7d0def90b4a540378f40f2fa04dc39f4_delferalpineftpserver_15622f
```

Any suggestions?

**Comment by JonathanFinch-awin** [comment]
For anyone using this container in GitHub Actions and finding it flaky. Passing the `--restart always` option seemed to solve the issue for me.
Example:
```
    services:
      ftp-server:
        image: delfer/alpine-ftp-server
        ports:
          - "21:21"
          - "21000-21010:21000-21010"
        env:
          USERS: "userone|5aahvl3KSx"
          ADDRESS: "localhost"
        options: >-
          --restart always
```
