### ISSUE TITLE
Container error illegal character with code 34 at position 0

### ISSUE THREAD

**Issue by kfbfarley** [delfer/docker-alpine-ftp-server#55]
My docker-compose.yml file

```
version: "3.7"
services:
  ftp:
    image: delfer/alpine-ftp-server:latest
    container_name: ftp
    env_file:
      - ~/docker/ftp.env
    volumes:
      - ftp-alpine:/home
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      - hub
    restart: unless-stopped

volumes:
  ftp-alpine:
    driver_opts:
      type: none
      device: /home/server/docker/ftp
      o: bind
    name: ftp-alpine

networks:
  hub:
    driver: bridge
```

Environment file:
```
TLS_CERT="~/docker/ftp.crt"
TLS_KEY="~/docker/ftp.key"
USERS="client|mypassword|/home/client"
```

Error:
```
Attaching to ftp
ftp    | adduser: illegal character with code 34 at position 0
ftp    | chown: unknown user/group "client:"client
```
