### ISSUE TITLE
environment seems wrong

### ISSUE THREAD

**Issue by chan15** [delfer/docker-alpine-ftp-server#63]
**failed**

```yml
alpine-ftp-server:
  image: delfer/alpine-ftp-server
  environment:
    - USERS="one|1234"
 ```

**success**

```yml
alpine-ftp-server:
  image: delfer/alpine-ftp-server
  environment:
    USERS: "one|1234"
 ```

**Comment by eduardonunesp** [comment]
yeh, it should be 

```yml
alpine-ftp-server:
  image: delfer/alpine-ftp-server
  environment:
    - USERS=one|1234
```

It was returning

```bash
{"data":{"status":"Error","message":"Login incorrect."}}
```

Login incorrect

on docker compose

```yml
services:
  ftp:
    image: delfer/alpine-ftp-server
    container_name: ftp
    restart: always
    ports:
      - "2121:21"
    environment:
      - USERS=one|1234
      - ADDRESS=0.0.0.0
```
