### ISSUE TITLE
mkdir: can't create directory '/ftp/admin': I/O error

### ISSUE THREAD

**Issue by geekyouth** [delfer/docker-alpine-ftp-server#65]
```yaml
services:
  ftp:
    image: delfer/alpine-ftp-server
    hostname: ftp
    container_name: ftp-dev
    restart: unless-stopped
    ports:
      - 21:21
      - 21000-21003:21000-21003
    environment:
      TZ: Asia/Shanghai
      USERS: "admin|ftp_dev_pass|/ftp/admin"
      ADDRESS: 192.168.3.100
      MIN_PORT: 21000
      MAX_PORT: 21003
    volumes:
      - ./_docker-data/ftp-dev/:/ftp/:rw
```

![image](https://github.com/delfer/docker-alpine-ftp-server/assets/12899262/3325d8c2-af75-492e-b4de-0ab6f914bfb2)
