### ISSUE TITLE
tini can't find start_vsftpd.sh

### ISSUE THREAD

**Issue by Tywele** [delfer/docker-alpine-ftp-server#72]
After pulling the latest code and creating a docker-compose.yml:

```yml
services:
  alpine-ftp-server:
    build: .
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - 21000-21010:21000-21010
    environment:
      - USERS="one|1234"
      - ADDRESS=localhost
```

and executing `docker-compose up --build` I get the following error after the docker container is build and starts to run: `alpine-ftp-server-1  | [FATAL tini (7)] exec /bin/start_vsftpd.sh failed: No such file or directory`. The container dies right after.

Running `docker run -d -p "21:21" -p 21000-21010:21000-21010 -e USERS="one|1234" -e ADDRESS=localhost delfer/alpine-ftp-server` leads to the same result.
