### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by ghost** [delfer/docker-alpine-ftp-server#76]
Hi there, I'm using this container

```yaml
$ cat docker-compose.yml
version: '3'
services:
  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - 21:21
      - 21000-21010:21000-21010
    environment:
      USERS: "user|SuperSecret|/home/user|1000"
   volumes:
     - "./data:/home"
```

Then I'm starting it

```
$ dcu
Recreating ftp-server_ftp_1 ... done
Attaching to ftp-server_ftp_1
ftp_1  | Changing password for user
ftp_1  | New password:
ftp_1  | Retype password:
ftp_1  | passwd: password for user changed by root
```

But if I'm trying to connect, it simply fails with:

```
$ ftp localhost
Trying [::1]:21 ...
ftp: Can't connect to `::1:21': Connection refused
Trying 127.0.0.1:21 ...
ftp: Can't connect to `127.0.0.1:21': Connection refused
ftp: Can't connect to `localhost:ftp'
```

But docker says that everything is fine:

```
$ dc ps
Name                    Command               State                                                                                        Ports
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ftp-server_ftp_1   /sbin/tini -- /bin/start_v ...   Up      0.0.0.0:32770->1281/tcp,:::32770->1281/tcp, 21/tcp, 0.0.0.0:21000->21000/tcp,:::21000->21000/tcp, 0.0.0.0:21001->21001/tcp,:::21001->21001/tcp,
0.0.0.0:21002->21002/tcp,:::21002->21002/tcp, 0.0.0.0:21003->21003/tcp,:::21003->21003/tcp, 0.0.0.0:21004->21004/tcp,:::21004->21004/tcp,
0.0.0.0:21005->21005/tcp,:::21005->21005/tcp, 0.0.0.0:21006->21006/tcp,:::21006->21006/tcp, 0.0.0.0:21007->21007/tcp,:::21007->21007/tcp,
0.0.0.0:21008->21008/tcp,:::21008->21008/tcp, 0.0.0.0:21009->21009/tcp,:::21009->21009/tcp, 0.0.0.0:21010->21010/tcp,:::21010->21010/tcp
$ docker ps
CONTAINER ID   IMAGE                                        COMMAND                  CREATED             STATUS                 PORTS                                                                                                       NAMES
ed8e2b030a37   delfer/alpine-ftp-server                     "/sbin/tini -- /bin/…"   6 minutes ago       Up 6 minutes           21/tcp, 0.0.0.0:21000-21010->21000-21010/tcp, :::21000-21010->21000-21010/tcp, 0.0.0.0:32770->1281/tcp, :::32770->1281/tcp   ftp-server_ftp_1
```

Am I missing something?
