### ISSUE TITLE
FTP rights

### ISSUE THREAD

**Issue by Graphandco** [delfer/docker-alpine-ftp-server#79]
Hello,

I can access my wordpress files by running an alpine ftp server. But I don’t have the correct rights to add or modify some files. I prefer not changing the folder rights, to avoid any issue with updates and uploads on the wordpress backoffice.

I am pretty sure it can me managed on my Dockerfile, but I didn’t figure how.

I tried to change this params in my ftp config 

`- USERS=graphandco|mypassword|/var/www/html|33|33`
Or
`- USERS=graphandco|mypassword|/var/www/html|33`

I also tried to add

`- ADDRESS=ftp.site.domain`

But cannot even connect to ftp with this params.

Maybe can I get a little help here ?

Thanks in advance

```
services:
  wordpress:
    image: 'wordpress:latest'
    volumes:
      - 'wordpress-files:/var/www/html'
    environment:
      - SERVICE_FQDN_WORDPRESS
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=$SERVICE_USER_WORDPRESS
      - WORDPRESS_DB_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mysql
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1'
      interval: 2s
      timeout: 10s
      retries: 10
  mysql:
    image: 'mysql:8'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=$SERVICE_USER_WORDPRESS
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - 127.0.0.1
      interval: 5s
      timeout: 20s
      retries: 10
  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - '8070:80'
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD_ROOT
  ftp:
    image: delfer/alpine-ftp-server
    network_mode: host
    ports:
      - '21:21'
      - '21000-21010:21000-21010'
    environment:
      - USERS=graphandco|mypassword|/var/www/html
    volumes:
      - 'wordpress-files:/var/www/html'
```
